### ISSUE TITLE
Register the RubberBandCircleTool in the ToolsRegistry

### ISSUE THREAD

**Issue by Hero-Solutions** [annotorious/annotorious-v2-selector-pack#1]
Registering the RubberBandCircleTool in the ToolsRegistry currently still happens in the main repository. This probably needs to moved to the selector pack. I'd do it myself, but I'm not sure what the preferred way is to do this.

**Comment by rsimon** [comment]
Thanks - missed that. Yes, the registration can be removed from the ToolsRegistry class. The SelectorPack plugin registers the circle implementation in index.js (when it calls .addDrawingTool).

**Comment by Hero-Solutions** [comment]
Oh, good. I hadn't noticed that calling .addDrawingTool also registers the drawing tool with the ToolsRegistry.

**Comment by Hero-Solutions** [comment]
Fixed in https://github.com/recogito/annotorious/pull/135.

**Comment by Hero-Solutions** [comment]
This issue can be closed as the circle drawing tool has been moved from the core distribution into the selector pack plugin.
