### ISSUE TITLE
Issue with executing `npm start` command.

### ISSUE THREAD

**Issue by yyhhkk12** [annotorious/annotorious-v2-selector-pack#10]
I met an error `Error: Cannot find module 'webpack-cli/bin/config-yargs'` while executing `npm start`.
According to [stackoverflow](https://stackoverflow.com/questions/40379139/cannot-find-module-webpack-bin-config-yargs), It looks webpack version is the cause of the error.
Thus, I changed start script in `package.json` from `"webpack-dev-server --open --mode=development -d"` to `webpack serve --open --mode=development`.
After changing script, I got another error `Error: Cannot find module '@babel/core'`. I solved this error by executing command `npm install --save-dev @babel/core`.

**Comment by rsimon** [comment]
Indeed - thanks for reporting! I fixed the webpack start config. Weirdly enough, when checking out from scratch and running an `npm install` (after the fix) I didn't need the babel core dependency, though. It was pulled automatically as part of the other babel deps. Looks like the build is working now, anyways... Thanks!
