### ISSUE TITLE
point tool bug

### ISSUE THREAD

**Issue by sinamcr7** [annotorious/annotorious-v2-selector-pack#22]
I'm using selector pack and formatters, it is ok for all shapes except point, its label is too large and doesn't fit in viewer:
![image](https://github.com/annotorious/annotorious-v2-selector-pack/assets/17440609/a1310ec9-20db-4ce9-a25e-6d8172ffa5d8)
please fix this bug
thanks in advance

**Comment by rsimon** [comment]
By label do you mean the formatter label (which I believe is shown left)? Or the popup (shown right)? Is the OSD viewer full-page size, or covers only part of the page? (In this case you might want to set `overflow` to `visible` with CSS.

**Comment by sinamcr7** [comment]
yeah formatter label, the issue is in the top right corner, it is so big and doesn't fit on page, here is a better image:
![image](https://github.com/annotorious/annotorious-v2-selector-pack/assets/17440609/1a75a282-0858-4e83-8ae5-bf518d839750)

**Comment by rsimon** [comment]
I found the culprit. This was not an issue with the Selector Pack, but with AnnotoriousOSD itself. If you need this urgently, you can re-build the fixed library from source yourself now. Otherwise: I'll publish a new release when I get the chance. Hopefully not too long.

**Comment by sinamcr7** [comment]
thank you so much

**Comment by rsimon** [comment]
Ah, I forgot to publish... fixed now! The new release 2.7.16 is online: https://www.npmjs.com/package/@recogito/annotorious-openseadragon
