### ISSUE TITLE
Point annotation tool

### ISSUE THREAD

**Issue by rsimon** [annotorious/annotorious-v2-selector-pack#6]
Since this would be pretty fundamental, it's probably worth including into the core distribution. (I.e. not as an extra plugin.)

**Comment by manfwh** [comment]
Any progress on this?

**Comment by rsimon** [comment]
Nothing has happened yet, I'm afraid. (There are a few minor tweaks needed inside Annotorious to make the point selection tool/icon work properly across zoom levels in responsive mode, and on OpenSeadragon.) I can't give a firm arrival date for this yet, but it's definitely coming... in the next month or so, fingers crossed.

**Comment by rsimon** [comment]
Point annotation tool is now available! 🎉 Make sure to use it __only__ with a recent release of Annotorious (v2.6.0+)

**Comment by sinamcr7** [comment]
hi, I'm using point tool and it just don't scale correctly when I change zoom lv unlike other tools, any fix for it?
also I need to change its style a bit to show whats behind it when I select it, is there any way to do this?

**Comment by rsimon** [comment]
The point annotation tool uses constant-size markers. They are supposed to keep the same size, regardless of the current scale. If you are looking for a circle that zooms along with the image, you are probably looking for the circle tool.

Both tools (point and circle) are rendered as SVG `circle` elements, and you can change their styles via CSS, in a very similar way than the built-in rectangle and polygon tools. Documentation for rectangle and polygon is here:

https://recogito.github.io/guides/customizing-styles/

Hope this helps!

**Comment by akasaurabhverma** [comment]
@rsimon I cannot find any point/circle tool. Can you please help me.

**Comment by rsimon** [comment]
Did you install the selector pack plugin properly? What does `anno.listDrawingTools()` say?

**Comment by HamzaFa61** [comment]
> Did you install the selector pack plugin properly? What does `anno.listDrawingTools()` say?

['rect', 'polygon']

It is only showing these two types of tools
