### ISSUE TITLE
Fixing the starting point of the circle

### ISSUE THREAD

**Issue by yyhhkk12** [annotorious/annotorious-v2-selector-pack#9]
Annotorious version: standard
Hello. I'm trying drawing circle annotation on image. When I drag the mouse to bottom right to draw a circle, starting point is fixed. But, other direction is not fixed.
I want to fix the starting point. Could you make a fix mode?

![g](https://user-images.githubusercontent.com/76547446/128808443-0c9f1186-897f-4a4f-af0b-515c650a1624.gif)

**Comment by rsimon** [comment]
The circle tool is a 3rd party contribution. I'm not sure whether the original author is still listening in here. A pull request would be great in case you want to make an attempt at fixing it: the code that handles the drawing is in this file:

https://github.com/recogito/annotorious-selector-pack/blob/main/src/circle/RubberbandCircle.js

Specifically the `dragTo` method.

**Comment by yyhhkk12** [comment]
I just sent a pull request(https://github.com/recogito/annotorious-selector-pack/pull/12). But, I don't know if it's right, so please review it.

**Comment by rsimon** [comment]
Wonderful - I reviewed, tested & just merged. Many thanks for the excellent fix!
